### ISSUE TITLE
Encrypting/decrypting data between multiple Spring Boot instances of the same application doesn't work

### ISSUE THREAD

**Issue by RadeKornjaca** [agoston/spring-data-mongodb-encrypt#58]
In a situation where multiple instances of the same Spring Boot applications use one, shared Mongo database, when one of them inserts document with a field marked as `@Encrypted` and other one tries to find it (using non-encrypted value in the query), it will fail.

Maybe it is my misunderstanding of what this library does, but is there a case when the above described scenario is achievable? Thank you very much!

**Comment by agoston** [comment]
As long as the key is the same, you can use multiple servers to access the same mongo instance (that is of course the most common use case, 1 mongo cluster and multiple backend servers).

The library does not influence the results of `.find()`. It merely decrypts fields that are encrypted in the results of `.find()`. I'd suggest to try test your queries in the mongodb console and/or in a simple scenario first.
