### ISSUE TITLE
Does this library support srping-boot-3.1.5?

### ISSUE THREAD

**Issue by owenJiao** [agoston/spring-data-mongodb-encrypt#60]
Hi Team,

  My project use spring-boot-3.1.5,  spring-data-mongo-3.1.5, when I use this library, it can't encrypt my data, so I wonder if it can be used in spring-boot-3.1.5.

  Thanks

**Comment by owenJiao** [comment]
I follow this configuration in this guide to do some test, but still can't encrypt data.

**Comment by agoston** [comment]
I upped spring-boot to 3.2.0 yesterday to check it, but it worked all right in all the system tests, so I think it's something that you do. Do check out the readme about this, there are a number of oversights one can easily make. Most importantly, remember that this library hooks into `MongoTemplate` 's `find()`, `save()`, ... methods. Individual field updates or direct mongodb driver accesses are bypassing it.

If you copy your code, I can help more.
