### ISSUE TITLE
How to verify data is encrypted or not ?

### ISSUE THREAD

**Issue by cshhahaha** [agoston/spring-data-mongodb-encrypt#62]
Hello agotson

I'm using your spring-data-mongodb-encrypt and success to save encrypted data into my mongodb.
But there are some exist data which is not encrypted (it means plain text data)

So encrypted data and plain text data are exist in my mongodb now.

I want to bypass decrypt process when load plain text data from mongodb.

Can you give an advise to me?

**Comment by agoston** [comment]
Hi!

You can set encryption to non-enforcing, as described here:

https://github.com/agoston/spring-data-mongodb-encrypt#ignore-decryption-failures

However, keep in mind that this should be a temporary measure only, as it silences failures. A proper data migration is recommended, followed up by turning off silent errors.

**Comment by cshhahaha** [comment]
> Hi!
> 
> You can set encryption to non-enforcing, as described here:
> 
> https://github.com/agoston/spring-data-mongodb-encrypt#ignore-decryption-failures
> 
> However, keep in mind that this should be a temporary measure only, as it silences failures. A proper data migration is recommended, followed up by turning off silent errors.

Thanks for answering !
