### ISSUE TITLE
Provide compatibility to Spring Boot 3.x version

### ISSUE THREAD

**Issue by KrisDaCoder** [agoston/spring-data-mongodb-encrypt#65]
I did an upgrade of my spring boot application from spring boot 2.7.18 to 3.3.3 which is quite an upgrade and it seems that the encryption is not working anymore. This can be viewed from the enabling DEBUG for MongoDB insertions. I can't seem to figure out exactly why it's not working from the debugging.

**Comment by KrisDaCoder** [comment]
I dropped down to 3.2.0 version and still same results. I also tried a manual configuration and still the same results.

**Comment by agoston** [comment]
Investigating.

**Comment by agoston** [comment]
Released version 2.9.1, can you try with that?

**Comment by KrisDaCoder** [comment]
Issue has been solved, thanks!
